Repository Denak39/MarvinBest-PWA, pull requests merged in 2023-09, with the labels that each got.

#10 feat: improve application
  .eslintrc
  .github/workflows/continuous-integration.yml
  .husky/pre-push
  .stylelintrc
  .validate-branch-namerc.cjs
  index.html
  package-lock.json
  package.json
  public/favicon.svg
  public/icons/1024.png
  public/icons/192.png
  public/icons/384.png
  public/icons/512.png
  public/icons/apple-touch-icon.png
  public/icons/browserconfig.xml
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon.ico
  public/icons/mstile-150x150.png
  public/icons/safari-pinned-tab.svg
  src/App.scss
  src/App.tsx
  src/app/api.ts
  src/app/hooks.ts
  src/app/middleware.ts
  src/app/sentence/sentenceSlice.ts
  src/app/store.ts
  src/main.tsx
  src/mock/user.ts
  src/mocks/type.ts
  src/mocks/user.ts
  src/sentence/SentenceForm.tsx
  src/shared/hooks/useOnlineStatus.ts
  src/styles/globals.scss
  src/useOnlineStatus.ts
  tsconfig.paths.json
  vite.config.ts
Labels: enhancement, github_actions, javascript

#11 feat: create avatar component
  .eslintrc
  .github/workflows/continuous-integration.yml
  .husky/pre-push
  package-lock.json
  package.json
  public/fonts/Montserrat/Montserrat-Light.ttf
  public/fonts/Montserrat/Montserrat-Light.woff2
  public/fonts/Montserrat/Montserrat-LightItalic.ttf
  public/fonts/Montserrat/Montserrat-LightItalic.woff2
  public/fonts/Montserrat/Montserrat-Medium.ttf
  public/fonts/Montserrat/Montserrat-Medium.woff2
  public/fonts/Montserrat/Montserrat-Regular.ttf
  public/fonts/Montserrat/Montserrat-Regular.woff2
  public/fonts/Montserrat/Montserrat-SemiBold.ttf
  public/fonts/Montserrat/Montserrat-SemiBold.woff2
  src/App.tsx
  src/shared/components/Avatar/Avatar.scss
  src/shared/components/Avatar/Avatar.test.tsx
  src/shared/components/Avatar/Avatar.tsx
  src/shared/components/Avatar/Avatar.types.ts
  src/styles/fonts.scss
  src/styles/globals.scss
  src/styles/index.scss
  src/styles/mixins.scss
  src/styles/variables.scss
  src/tests/setup.ts
  tsconfig.json
  tsconfig.paths.json
  vite.config.ts
Labels: enhancement, javascript

#14 feat: create message component
  .eslintrc
  .gitignore
  package-lock.json
  package.json
  src/helpers/DateHelpers.test.ts
  src/helpers/DateHelpers.ts
  src/shared/components/Avatar/Avatar.test.tsx
  src/shared/components/Message/Message.scss
  src/shared/components/Message/Message.test.tsx
  src/shared/components/Message/Message.tsx
  src/shared/components/Message/Message.types.ts
  src/styles/mixins.scss
  tsconfig.paths.json
  vite.config.ts
Labels: enhancement, javascript

#13 feat: create navbar component
  .gitignore
  package-lock.json
  public/images/mask.svg
  src/App.scss
  src/App.tsx
  src/constants/index.ts
  src/shared/components/Icons/IconAdd.tsx
  src/shared/components/Icons/IconHome.tsx
  src/shared/components/Icons/IconUsers.tsx
  src/shared/components/NavBar/NavBar.scss
  src/shared/components/NavBar/NavBar.test.tsx
  src/shared/components/NavBar/NavBar.tsx
  src/styles/index.scss
  src/styles/variables.scss
  tsconfig.json
  vite.config.ts
Labels: enhancement, javascript

#15 feat: people page
  .env.sample
  .eslintrc
  .gitignore
  index.html
  src/App.tsx
  src/api/helpers.ts
  src/api/index.ts
  src/api/parsers.ts
  src/api/types.ts
  src/app/hooks.ts
  src/app/store.ts
  src/app/types.ts
  src/constants/index.ts
  src/helpers/DateHelpers.ts
  src/home/HomePage.tsx
  src/people/components/PeoplePage.tsx
  src/people/parsers.ts
  src/people/selectors.ts
  src/people/slice.ts
  src/people/styles/PeoplePage.scss
  src/people/types.ts
  src/sentences/components/SentenceForm.tsx
  src/sentences/parsers.ts
  src/sentences/types.ts
  src/shared/components/Avatar/Avatar.scss
  src/shared/components/Avatar/Avatar.test.tsx
  src/shared/components/Avatar/Avatar.tsx
  src/shared/components/Avatar/Avatar.types.ts
  src/shared/components/Card/Card.scss
  src/shared/components/Card/Card.test.tsx
  src/shared/components/Card/Card.tsx
  src/shared/components/Card/Card.types.ts
  src/shared/components/Header/Header.scss
  src/shared/components/Header/Header.test.tsx
  src/shared/components/Header/Header.tsx
  src/shared/components/Header/Header.types.ts
  src/shared/components/Icons/IconArrowForward.tsx
  src/shared/components/Layout/Layout.scss
  src/shared/components/Layout/Layout.test.tsx
  src/shared/components/Layout/Layout.tsx
  src/shared/components/Message/Message.test.tsx
  src/shared/components/Message/Message.tsx
  src/shared/components/Message/Message.types.ts
  src/shared/components/NavBar/NavBar.scss
  src/shared/components/NavBar/NavBar.test.tsx
  src/shared/components/NavBar/NavBar.tsx
  src/shared/hooks/useScrolledToBottom.ts
  src/styles/functions.scss
  src/styles/index.scss
  src/styles/mixins.scss
  src/tests/index.tsx
  tsconfig.paths.json
  vite.config.ts
Labels: enhancement, javascript

#30 feat: alert offline
  src/people/components/PersonPage.tsx
  src/shared/components/Alert/Alert.scss
  src/shared/components/Alert/Alert.test.tsx
  src/shared/components/Alert/Alert.tsx
  src/shared/components/Alert/Alert.types.ts
  src/shared/components/Icons/IconOffline.tsx
  src/shared/components/Layout/Layout.scss
  src/shared/components/Layout/Layout.tsx
  src/shared/components/NavBar/NavBar.tsx
Labels: enhancement, javascript

#27 feat: error page
  .eslintrc
  public/images/mascot-marvin-best-sad.png
  src/App.tsx
  src/people/components/PeoplePage.tsx
  src/people/components/PersonPage.tsx
  src/people/styles/PeoplePage.scss
  src/people/styles/PersonPage.scss
  src/sentences/styles/SentenceForm.scss
  src/shared/components/ErrorPage/BaseErrorPage/BaseErrorPage.scss
  src/shared/components/ErrorPage/BaseErrorPage/BaseErrorPage.test.tsx
  src/shared/components/ErrorPage/BaseErrorPage/BaseErrorPage.tsx
  src/shared/components/ErrorPage/BaseErrorPage/BaseErrorPage.types.ts
  src/shared/components/ErrorPage/ErrorPage.tsx
  src/shared/components/ErrorPage/NotFoundPage.tsx
  src/shared/components/Header/Header.scss
  src/shared/components/Header/Header.test.tsx
  src/shared/components/IconButton/IconButton.tsx
  src/shared/components/NavBar/NavBar.scss
  src/shared/components/NavBar/NavBar.tsx
  src/styles/global.scss
  src/styles/index.scss
  tsconfig.paths.json
  vite.config.ts
Labels: enhancement, javascript

#31 feat: add button style in error page
  .eslintrc
  src/images/mascot-marvin-best-sad.png
  src/sentences/components/SentenceFormPage.tsx
  src/sentences/styles/SentenceForm.scss
  src/shared/components/Button/Button.scss
  src/shared/components/Button/Button.tsx
  src/shared/components/ErrorPage/BaseErrorPage/BaseErrorPage.tsx
  src/styles/index.scss
  tsconfig.paths.json
  vite.config.ts
Labels: javascript
